//! Protocol definitions and generated code for the Cadence client.
//!
//! This crate contains the Protobuf/gRPC definitions for communicating
//! with the Cadence server.

// gRPC-generated code from proto files
// These modules are generated by tonic-build from the .proto files
// in the proto/ directory during the build process
pub mod generated;

// Manual protocol type definitions (wrapper types around generated code)
pub mod shared;
pub mod workflow_service;

// Type conversions between hand-written API types and generated protobuf types
pub mod conversions;

pub use shared::*;
pub use workflow_service::*;

// Re-export tonic and prost for use by other crates
pub use prost;
pub use tonic;
