//! Protocol definitions and generated code for the Cadence client.
//!
//! This crate contains the Thrift and Protobuf definitions for communicating
//! with the Cadence server.

// Thrift-generated code from IDL files
// These modules are generated by the Apache Thrift compiler from the IDL files
// in the thrift/ directory. To regenerate, run: ./scripts/generate-thrift.sh
pub mod generated;

// Manual protocol type definitions (to be gradually replaced by generated types)
pub mod shared;
pub mod workflow_service;

// Type conversions between thrift and internal types
pub mod conversions;

pub use shared::*;
pub use workflow_service::*;

// Re-export thrift crate for use by other crates
pub use thrift;
